// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: student_task.proto

package education_management_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StudentTaskService_GetByID_FullMethodName               = "/education_management_service.StudentTaskService/GetByID"
	StudentTaskService_GetList_FullMethodName               = "/education_management_service.StudentTaskService/GetList"
	StudentTaskService_Create_FullMethodName                = "/education_management_service.StudentTaskService/Create"
	StudentTaskService_Update_FullMethodName                = "/education_management_service.StudentTaskService/Update"
	StudentTaskService_Delete_FullMethodName                = "/education_management_service.StudentTaskService/Delete"
	StudentTaskService_GetByIDStudent_FullMethodName        = "/education_management_service.StudentTaskService/GetByIDStudent"
	StudentTaskService_UpdateScoreforTeacher_FullMethodName = "/education_management_service.StudentTaskService/UpdateScoreforTeacher"
	StudentTaskService_UpdateScoreforStudent_FullMethodName = "/education_management_service.StudentTaskService/UpdateScoreforStudent"
)

// StudentTaskServiceClient is the client API for StudentTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentTaskServiceClient interface {
	GetByID(ctx context.Context, in *StudentTaskID, opts ...grpc.CallOption) (*GetStudentTaskResponse, error)
	GetList(ctx context.Context, in *GetListStudentTaskRequest, opts ...grpc.CallOption) (*GetListStudentTaskResponse, error)
	Create(ctx context.Context, in *CreateStudentTaskRequest, opts ...grpc.CallOption) (*StudentTaskResponse, error)
	Update(ctx context.Context, in *UpdateStudentTaskRequest, opts ...grpc.CallOption) (*GetStudentTaskResponse, error)
	Delete(ctx context.Context, in *StudentTaskID, opts ...grpc.CallOption) (*StudentTaskEmpty, error)
	GetByIDStudent(ctx context.Context, in *TaskStudentID, opts ...grpc.CallOption) (*GetStudentTaskResponse, error)
	UpdateScoreforTeacher(ctx context.Context, in *UpdateStudentScoreRequest, opts ...grpc.CallOption) (*GetStudentTaskResponse, error)
	UpdateScoreforStudent(ctx context.Context, in *UpdateStudentScoreRequest, opts ...grpc.CallOption) (*GetStudentTaskResponse, error)
}

type studentTaskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentTaskServiceClient(cc grpc.ClientConnInterface) StudentTaskServiceClient {
	return &studentTaskServiceClient{cc}
}

func (c *studentTaskServiceClient) GetByID(ctx context.Context, in *StudentTaskID, opts ...grpc.CallOption) (*GetStudentTaskResponse, error) {
	out := new(GetStudentTaskResponse)
	err := c.cc.Invoke(ctx, StudentTaskService_GetByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentTaskServiceClient) GetList(ctx context.Context, in *GetListStudentTaskRequest, opts ...grpc.CallOption) (*GetListStudentTaskResponse, error) {
	out := new(GetListStudentTaskResponse)
	err := c.cc.Invoke(ctx, StudentTaskService_GetList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentTaskServiceClient) Create(ctx context.Context, in *CreateStudentTaskRequest, opts ...grpc.CallOption) (*StudentTaskResponse, error) {
	out := new(StudentTaskResponse)
	err := c.cc.Invoke(ctx, StudentTaskService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentTaskServiceClient) Update(ctx context.Context, in *UpdateStudentTaskRequest, opts ...grpc.CallOption) (*GetStudentTaskResponse, error) {
	out := new(GetStudentTaskResponse)
	err := c.cc.Invoke(ctx, StudentTaskService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentTaskServiceClient) Delete(ctx context.Context, in *StudentTaskID, opts ...grpc.CallOption) (*StudentTaskEmpty, error) {
	out := new(StudentTaskEmpty)
	err := c.cc.Invoke(ctx, StudentTaskService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentTaskServiceClient) GetByIDStudent(ctx context.Context, in *TaskStudentID, opts ...grpc.CallOption) (*GetStudentTaskResponse, error) {
	out := new(GetStudentTaskResponse)
	err := c.cc.Invoke(ctx, StudentTaskService_GetByIDStudent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentTaskServiceClient) UpdateScoreforTeacher(ctx context.Context, in *UpdateStudentScoreRequest, opts ...grpc.CallOption) (*GetStudentTaskResponse, error) {
	out := new(GetStudentTaskResponse)
	err := c.cc.Invoke(ctx, StudentTaskService_UpdateScoreforTeacher_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentTaskServiceClient) UpdateScoreforStudent(ctx context.Context, in *UpdateStudentScoreRequest, opts ...grpc.CallOption) (*GetStudentTaskResponse, error) {
	out := new(GetStudentTaskResponse)
	err := c.cc.Invoke(ctx, StudentTaskService_UpdateScoreforStudent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentTaskServiceServer is the server API for StudentTaskService service.
// All implementations must embed UnimplementedStudentTaskServiceServer
// for forward compatibility
type StudentTaskServiceServer interface {
	GetByID(context.Context, *StudentTaskID) (*GetStudentTaskResponse, error)
	GetList(context.Context, *GetListStudentTaskRequest) (*GetListStudentTaskResponse, error)
	Create(context.Context, *CreateStudentTaskRequest) (*StudentTaskResponse, error)
	Update(context.Context, *UpdateStudentTaskRequest) (*GetStudentTaskResponse, error)
	Delete(context.Context, *StudentTaskID) (*StudentTaskEmpty, error)
	GetByIDStudent(context.Context, *TaskStudentID) (*GetStudentTaskResponse, error)
	UpdateScoreforTeacher(context.Context, *UpdateStudentScoreRequest) (*GetStudentTaskResponse, error)
	UpdateScoreforStudent(context.Context, *UpdateStudentScoreRequest) (*GetStudentTaskResponse, error)
	mustEmbedUnimplementedStudentTaskServiceServer()
}

// UnimplementedStudentTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStudentTaskServiceServer struct {
}

func (UnimplementedStudentTaskServiceServer) GetByID(context.Context, *StudentTaskID) (*GetStudentTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedStudentTaskServiceServer) GetList(context.Context, *GetListStudentTaskRequest) (*GetListStudentTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedStudentTaskServiceServer) Create(context.Context, *CreateStudentTaskRequest) (*StudentTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedStudentTaskServiceServer) Update(context.Context, *UpdateStudentTaskRequest) (*GetStudentTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedStudentTaskServiceServer) Delete(context.Context, *StudentTaskID) (*StudentTaskEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedStudentTaskServiceServer) GetByIDStudent(context.Context, *TaskStudentID) (*GetStudentTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIDStudent not implemented")
}
func (UnimplementedStudentTaskServiceServer) UpdateScoreforTeacher(context.Context, *UpdateStudentScoreRequest) (*GetStudentTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateScoreforTeacher not implemented")
}
func (UnimplementedStudentTaskServiceServer) UpdateScoreforStudent(context.Context, *UpdateStudentScoreRequest) (*GetStudentTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateScoreforStudent not implemented")
}
func (UnimplementedStudentTaskServiceServer) mustEmbedUnimplementedStudentTaskServiceServer() {}

// UnsafeStudentTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentTaskServiceServer will
// result in compilation errors.
type UnsafeStudentTaskServiceServer interface {
	mustEmbedUnimplementedStudentTaskServiceServer()
}

func RegisterStudentTaskServiceServer(s grpc.ServiceRegistrar, srv StudentTaskServiceServer) {
	s.RegisterService(&StudentTaskService_ServiceDesc, srv)
}

func _StudentTaskService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentTaskID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentTaskServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentTaskService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentTaskServiceServer).GetByID(ctx, req.(*StudentTaskID))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentTaskService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListStudentTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentTaskServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentTaskService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentTaskServiceServer).GetList(ctx, req.(*GetListStudentTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentTaskService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStudentTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentTaskServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentTaskService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentTaskServiceServer).Create(ctx, req.(*CreateStudentTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentTaskService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentTaskServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentTaskService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentTaskServiceServer).Update(ctx, req.(*UpdateStudentTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentTaskService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentTaskID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentTaskServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentTaskService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentTaskServiceServer).Delete(ctx, req.(*StudentTaskID))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentTaskService_GetByIDStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStudentID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentTaskServiceServer).GetByIDStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentTaskService_GetByIDStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentTaskServiceServer).GetByIDStudent(ctx, req.(*TaskStudentID))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentTaskService_UpdateScoreforTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentTaskServiceServer).UpdateScoreforTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentTaskService_UpdateScoreforTeacher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentTaskServiceServer).UpdateScoreforTeacher(ctx, req.(*UpdateStudentScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentTaskService_UpdateScoreforStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStudentScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentTaskServiceServer).UpdateScoreforStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentTaskService_UpdateScoreforStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentTaskServiceServer).UpdateScoreforStudent(ctx, req.(*UpdateStudentScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudentTaskService_ServiceDesc is the grpc.ServiceDesc for StudentTaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudentTaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "education_management_service.StudentTaskService",
	HandlerType: (*StudentTaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByID",
			Handler:    _StudentTaskService_GetByID_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _StudentTaskService_GetList_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _StudentTaskService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _StudentTaskService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StudentTaskService_Delete_Handler,
		},
		{
			MethodName: "GetByIDStudent",
			Handler:    _StudentTaskService_GetByIDStudent_Handler,
		},
		{
			MethodName: "UpdateScoreforTeacher",
			Handler:    _StudentTaskService_UpdateScoreforTeacher_Handler,
		},
		{
			MethodName: "UpdateScoreforStudent",
			Handler:    _StudentTaskService_UpdateScoreforStudent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "student_task.proto",
}
