// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: support_teacher.proto

package user_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SupportTeacherService_Create_FullMethodName        = "/user_service.SupportTeacherService/Create"
	SupportTeacherService_GetByID_FullMethodName       = "/user_service.SupportTeacherService/GetByID"
	SupportTeacherService_GetList_FullMethodName       = "/user_service.SupportTeacherService/GetList"
	SupportTeacherService_Update_FullMethodName        = "/user_service.SupportTeacherService/Update"
	SupportTeacherService_Delete_FullMethodName        = "/user_service.SupportTeacherService/Delete"
	SupportTeacherService_GetReportList_FullMethodName = "/user_service.SupportTeacherService/GetReportList"
)

// SupportTeacherServiceClient is the client API for SupportTeacherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupportTeacherServiceClient interface {
	Create(ctx context.Context, in *CreateSupportTeacherRequest, opts ...grpc.CallOption) (*SupportTeacherResponse, error)
	GetByID(ctx context.Context, in *SupportTeacherID, opts ...grpc.CallOption) (*GetSupportTeacherResponse, error)
	GetList(ctx context.Context, in *GetListSupportTeacherRequest, opts ...grpc.CallOption) (*GetListSupportTeacherResponse, error)
	Update(ctx context.Context, in *UpdateSupportTeacherRequest, opts ...grpc.CallOption) (*GetSupportTeacherResponse, error)
	Delete(ctx context.Context, in *SupportTeacherID, opts ...grpc.CallOption) (*SupportTeacherEmpty, error)
	GetReportList(ctx context.Context, in *GetReportListSupportTeacherRequest, opts ...grpc.CallOption) (*GetReportListSupportTeacherResponse, error)
}

type supportTeacherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupportTeacherServiceClient(cc grpc.ClientConnInterface) SupportTeacherServiceClient {
	return &supportTeacherServiceClient{cc}
}

func (c *supportTeacherServiceClient) Create(ctx context.Context, in *CreateSupportTeacherRequest, opts ...grpc.CallOption) (*SupportTeacherResponse, error) {
	out := new(SupportTeacherResponse)
	err := c.cc.Invoke(ctx, SupportTeacherService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportTeacherServiceClient) GetByID(ctx context.Context, in *SupportTeacherID, opts ...grpc.CallOption) (*GetSupportTeacherResponse, error) {
	out := new(GetSupportTeacherResponse)
	err := c.cc.Invoke(ctx, SupportTeacherService_GetByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportTeacherServiceClient) GetList(ctx context.Context, in *GetListSupportTeacherRequest, opts ...grpc.CallOption) (*GetListSupportTeacherResponse, error) {
	out := new(GetListSupportTeacherResponse)
	err := c.cc.Invoke(ctx, SupportTeacherService_GetList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportTeacherServiceClient) Update(ctx context.Context, in *UpdateSupportTeacherRequest, opts ...grpc.CallOption) (*GetSupportTeacherResponse, error) {
	out := new(GetSupportTeacherResponse)
	err := c.cc.Invoke(ctx, SupportTeacherService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportTeacherServiceClient) Delete(ctx context.Context, in *SupportTeacherID, opts ...grpc.CallOption) (*SupportTeacherEmpty, error) {
	out := new(SupportTeacherEmpty)
	err := c.cc.Invoke(ctx, SupportTeacherService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportTeacherServiceClient) GetReportList(ctx context.Context, in *GetReportListSupportTeacherRequest, opts ...grpc.CallOption) (*GetReportListSupportTeacherResponse, error) {
	out := new(GetReportListSupportTeacherResponse)
	err := c.cc.Invoke(ctx, SupportTeacherService_GetReportList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupportTeacherServiceServer is the server API for SupportTeacherService service.
// All implementations must embed UnimplementedSupportTeacherServiceServer
// for forward compatibility
type SupportTeacherServiceServer interface {
	Create(context.Context, *CreateSupportTeacherRequest) (*SupportTeacherResponse, error)
	GetByID(context.Context, *SupportTeacherID) (*GetSupportTeacherResponse, error)
	GetList(context.Context, *GetListSupportTeacherRequest) (*GetListSupportTeacherResponse, error)
	Update(context.Context, *UpdateSupportTeacherRequest) (*GetSupportTeacherResponse, error)
	Delete(context.Context, *SupportTeacherID) (*SupportTeacherEmpty, error)
	GetReportList(context.Context, *GetReportListSupportTeacherRequest) (*GetReportListSupportTeacherResponse, error)
	mustEmbedUnimplementedSupportTeacherServiceServer()
}

// UnimplementedSupportTeacherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSupportTeacherServiceServer struct {
}

func (UnimplementedSupportTeacherServiceServer) Create(context.Context, *CreateSupportTeacherRequest) (*SupportTeacherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSupportTeacherServiceServer) GetByID(context.Context, *SupportTeacherID) (*GetSupportTeacherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedSupportTeacherServiceServer) GetList(context.Context, *GetListSupportTeacherRequest) (*GetListSupportTeacherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedSupportTeacherServiceServer) Update(context.Context, *UpdateSupportTeacherRequest) (*GetSupportTeacherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSupportTeacherServiceServer) Delete(context.Context, *SupportTeacherID) (*SupportTeacherEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSupportTeacherServiceServer) GetReportList(context.Context, *GetReportListSupportTeacherRequest) (*GetReportListSupportTeacherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReportList not implemented")
}
func (UnimplementedSupportTeacherServiceServer) mustEmbedUnimplementedSupportTeacherServiceServer() {}

// UnsafeSupportTeacherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupportTeacherServiceServer will
// result in compilation errors.
type UnsafeSupportTeacherServiceServer interface {
	mustEmbedUnimplementedSupportTeacherServiceServer()
}

func RegisterSupportTeacherServiceServer(s grpc.ServiceRegistrar, srv SupportTeacherServiceServer) {
	s.RegisterService(&SupportTeacherService_ServiceDesc, srv)
}

func _SupportTeacherService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupportTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportTeacherServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportTeacherService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportTeacherServiceServer).Create(ctx, req.(*CreateSupportTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportTeacherService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportTeacherID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportTeacherServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportTeacherService_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportTeacherServiceServer).GetByID(ctx, req.(*SupportTeacherID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportTeacherService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListSupportTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportTeacherServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportTeacherService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportTeacherServiceServer).GetList(ctx, req.(*GetListSupportTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportTeacherService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSupportTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportTeacherServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportTeacherService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportTeacherServiceServer).Update(ctx, req.(*UpdateSupportTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportTeacherService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportTeacherID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportTeacherServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportTeacherService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportTeacherServiceServer).Delete(ctx, req.(*SupportTeacherID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportTeacherService_GetReportList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportListSupportTeacherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportTeacherServiceServer).GetReportList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportTeacherService_GetReportList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportTeacherServiceServer).GetReportList(ctx, req.(*GetReportListSupportTeacherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SupportTeacherService_ServiceDesc is the grpc.ServiceDesc for SupportTeacherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupportTeacherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_service.SupportTeacherService",
	HandlerType: (*SupportTeacherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SupportTeacherService_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _SupportTeacherService_GetByID_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _SupportTeacherService_GetList_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SupportTeacherService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SupportTeacherService_Delete_Handler,
		},
		{
			MethodName: "GetReportList",
			Handler:    _SupportTeacherService_GetReportList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "support_teacher.proto",
}
